#
# use %make -r
#	"-r" option will ignore /usr/include/make/default.mk
#
#
#
#
all:
	@echo All done making PostScript
	@echo The final output is *.ps TEXT/*.dvi

cleanup:
	cd TEXT; make -r cleanup
	@echo All done cleaning

clean:
	cd TEXT; make -r clean
#
